name         'mcanevet-freebox'
version      '0.0.1'
source       'https://github.com/mcanevet/puppet-freebox'
author       'Mickaël Canévet'
license      'Apache 2.0'
summary      'Puppet module for Freebox'
description  'The Freebox OS module allows you to easily manage the Freebox Server settings in Puppet via the FreeboxOS Gateway API.'
project_page 'https://github.com/mcanevet/puppet-freebox'

dependency   'puppetlabs/inifile', '1.x'
